version: "3.8"

services:
  broker:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - type: bind
        source: ./config/broker/config/mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  generator:
    image: phonenumbers/generator
    build:
      context: .
      dockerfile: ./services/generator/Dockerfile
    depends_on:
      - broker
    environment:
      MIN: 10_000_000_000
      MAX: 999_999_999_999
      BROKER_URL: "mqtt://broker"
      PUBLISH_TOPIC: numbers/raw
  metadata:
    image: phonenumbers/metadata
    build:
      context: .
      dockerfile: ./services/metadata/Dockerfile
    depends_on:
      - broker
    environment:
      BROKER_URL: "mqtt://broker"
      PUBLISH_TOPIC: numbers/enriched
      SUBSCRIBE_TOPIC: numbers/raw
  store:
    image: phonenumbers/store
    build:
      context: .
      dockerfile: ./services/store/Dockerfile
    depends_on:
      - db
      - broker
    environment:
      DB_URI: "mongodb://db/numbers"
      BROKER_URL: "mqtt://broker"
      SUBSCRIBE_TOPIC: numbers/enriched

